packages:
  - packages/*
  - packages/builders/*
  - docs
  - playground
  - examples/*
  - tooling/*

catalogs:
  actions:
    '@actions/core': 1.11.1

  builders:
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-typescript': 12.3.0
    '@rspack/core': 1.7.4
    '@swc/core': 1.15.11
    esbuild: 0.27.2
    rolldown: 1.0.0-rc.2
    rollup: 4.57.1
    swc-loader: 0.2.7
    vite: 7.2.4
    webpack: 5.103.0

  dev:
    publint: 0.3.17
    tsdown: 0.20.1
    typescript: 5.9.3

  docs:
    '@cloudflare/vite-plugin': 1.22.1
    vitepress: 1.6.4
    vitepress-plugin-group-icons: 1.7.1
    wrangler: 4.61.1

  linting:
    '@luxass/eslint-config': 6.0.3
    eslint: 9.39.2
    eslint-plugin-format: 1.3.1

  monorepo:
    '@changesets/changelog-github': 0.5.2
    '@changesets/cli': 2.29.8
    turbo: 2.8.1

  prod:
    '@clack/prompts': 0.11.0
    c12: 3.3.3
    cac: 6.7.14
    consola: 3.4.2
    defu: 6.1.4
    farver: 0.4.2
    zod: 4.3.6

  templates:
    '@actions-sdk/esbuild-builder': latest
    '@actions-sdk/rolldown-builder': latest
    '@actions-sdk/rollup-builder': latest
    '@actions-sdk/rspack-builder': latest
    '@actions-sdk/vite-builder': latest
    '@actions-sdk/webpack-builder': latest
    actions-kit: latest

  testing:
    '@vitest/coverage-v8': 4.0.13
    vitest: 4.0.13
    vitest-testdirs: 4.4.2

  types:
    '@types/node': 24.10.9

  unplugin:
    '@rollup/pluginutils': 5.3.0
    yaml: 2.8.2
    ts-loader: 9.5.4
    tslib: 2.8.1
    unplugin: 2.3.11

engineStrict: true

linkWorkspacePackages: true

overrides:
  vite: catalog:builders
  rolldown: catalog:builders

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: false
