packages:
  # don't use /** because then it would match templates also
  - packages/*
  - packages/builders/*
  - docs
  - playground
  - examples/*
catalog:
  "@actions/core": ^1.11.1
  "@biomejs/biome": ^1.9.3
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.7
  "@rollup/plugin-commonjs": ^28.0.0
  "@rollup/plugin-node-resolve": ^15.3.0
  "@rollup/plugin-typescript": ^12.1.1
  "@rollup/pluginutils": ^5.1.2
  "@rspack/core": ^1.0.13
  "@swc/core": ^1.7.39
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.16.11
  c12: ^2.0.1
  cac: ^6.7.14
  consola: ^3.2.3
  defu: ^6.1.4
  esbuild: ^0.24.0
  js-yaml: ^4.1.0
  rolldown: ^0.13.2
  rollup: ^4.24.0
  swc-loader: ^0.2.6
  ts-loader: ^9.5.1
  tslib: ^2.8.0
  tsup: ^8.3.0
  turbo: ^2.2.1
  typescript: ^5.6.3
  unplugin: ^1.14.1
  vite: ^5.4.8
  vitepress: ^1.4.1
  vitepress-plugin-group-icons: ^1.3.0
  vitest: ^2.1.3
  vitest-testdirs: ^1.1.0
  webpack: ^5.95.0
  zod: ^3.23.8
  farver: ^0.2.0
