packages:
  - packages/*
  - docs
  - playground
  - examples/*

catalog:
  "@actions/core": ^1.11.1
  "@biomejs/biome": ^1.9.3
  "@rollup/plugin-typescript": ^12.1.1
  "@rollup/plugin-node-resolve": ^15.3.0
  "@rollup/plugin-commonjs": ^28.0.0
  "@rollup/pluginutils": ^5.1.2
  "@rspack/core": ^1.0.13
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.16.11
  cac: ^6.7.14
  turbo: ^2.2.1
  consola: ^3.2.3
  esbuild: ^0.24.0
  js-yaml: ^4.1.0
  rolldown: ^0.13.2
  rollup: ^4.24.0
  ts-loader: ^9.5.1
  tslib: ^2.8.0
  tsup: ^8.3.0
  typescript: ^5.6.3
  unplugin: ^1.14.1
  vite: ^5.4.8
  vitepress: ^1.4.1
  vitest: ^2.1.3
  vitest-testdirs: ^1.1.0
  webpack: ^5.95.0
  zod: ^3.23.8
  c12: ^2.0.1
  defu: ^6.1.4
