packages:
  - packages/*
  - docs

catalog:
  "@types/node": ^20.16.11
  tsup: ^8.3.0
  typescript: ^5.6.3
  vitest: ^2.1.3
  zod: ^3.23.8
  cac: ^6.7.14
  consola: ^3.2.3
  "@actions/core": ^1.11.1
  "@biomejs/biome": ^1.9.4
