packages:
  - packages/*
  - packages/builders/*
  - docs
  - playground
  - examples/*
  - tooling/*

catalogs:
  actions:
    '@actions/core': 1.11.1
  builders:
    '@rollup/plugin-commonjs': 28.0.6
    '@rollup/plugin-node-resolve': 16.0.1
    '@rollup/plugin-typescript': 12.1.4
    '@rspack/core': 1.5.2
    '@swc/core': 1.13.5
    esbuild: 0.25.9
    rolldown: 1.0.0-beta.34
    rollup: 4.50.0
    swc-loader: 0.2.6
    vite: 7.1.7
    webpack: 5.101.3
  dev:
    publint: 0.3.12
    tsdown: 0.14.2
    typescript: 5.9.2
  docs:
    '@cloudflare/vite-plugin': 1.12.2
    vitepress: 1.6.4
    vitepress-plugin-group-icons: 1.6.3
    wrangler: 4.33.2
  linting:
    '@luxass/eslint-config': 5.3.1
    eslint: 9.33.0
    eslint-plugin-format: ^1.0.1
  monorepo:
    '@changesets/changelog-github': 0.5.1
    '@changesets/cli': 2.29.6
    turbo: 2.5.6
  prod:
    '@clack/prompts': 0.11.0
    c12: 3.2.0
    cac: 6.7.14
    consola: 3.4.2
    defu: 6.1.4
    farver: 0.4.2
    zod: 4.1.5
  templates:
    '@actions-sdk/esbuild-builder': latest
    '@actions-sdk/rolldown-builder': latest
    '@actions-sdk/rollup-builder': latest
    '@actions-sdk/rspack-builder': latest
    '@actions-sdk/vite-builder': latest
    '@actions-sdk/webpack-builder': latest
    actions-kit: latest
  testing:
    '@vitest/coverage-v8': 3.2.4
    vitest: 3.2.4
    vitest-testdirs: 4.2.0
  types:
    '@types/js-yaml': 4.0.9
    '@types/node': 22.18.0
  unplugin:
    '@rollup/pluginutils': 5.2.0
    js-yaml: 4.1.0
    ts-loader: 9.5.4
    tslib: 2.8.1
    unplugin: 2.3.10

engineStrict: true

linkWorkspacePackages: true

overrides:
  vite: catalog:builders

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: false
