packages:
  - packages/*
  - packages/builders/*
  - docs
  - playground
  - examples/*
catalog:
  '@actions/core': ^1.11.1
  '@biomejs/biome': ^1.9.4
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.12
  '@rollup/plugin-commonjs': ^28.0.2
  '@rollup/plugin-node-resolve': ^16.0.0
  '@rollup/plugin-typescript': ^12.1.2
  '@rollup/pluginutils': ^5.1.4
  '@rspack/core': ^1.2.2
  '@swc/core': ^1.10.12
  '@types/js-yaml': ^4.0.9
  '@types/node': ^22.0.0
  c12: ^2.0.1
  cac: ^6.7.14
  consola: ^3.4.0
  defu: ^6.1.4
  esbuild: ^0.25.0
  farver: ^0.4.0
  js-yaml: ^4.1.0
  rolldown: 1.0.0-beta.3
  rollup: ^4.32.1
  swc-loader: ^0.2.6
  ts-loader: ^9.5.2
  tslib: ^2.8.1
  tsup: ^8.3.6
  turbo: ^2.3.4
  typescript: ^5.7.3
  unplugin: ^2.0.0
  vite: ^6.0.0
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.4
  vitest-testdirs: ^2.1.1
  webpack: ^5.97.1
  zod: ^3.24.1
