packages:
  - packages/*
  - packages/builders/*
  - docs
  - playground
  - examples/*
  - tooling/*

catalogs:
  actions:
    '@actions/core': 1.11.1
  builders:
    '@rollup/plugin-commonjs': 28.0.9
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-typescript': 12.3.0
    '@rspack/core': 1.5.8
    '@swc/core': 1.13.21
    esbuild: 0.25.11
    rolldown: 1.0.0-beta.44
    rollup: 4.52.5
    swc-loader: 0.2.6
    vite: 7.1.11
    webpack: 5.102.1
  dev:
    publint: 0.3.15
    tsdown: 0.15.9
    typescript: 5.9.3
  docs:
    '@cloudflare/vite-plugin': 1.13.15
    vitepress: 1.6.4
    vitepress-plugin-group-icons: 1.6.5
    wrangler: 4.45.0
  linting:
    '@luxass/eslint-config': 6.0.1
    eslint: 9.36.0
    eslint-plugin-format: 1.0.2
  monorepo:
    '@changesets/changelog-github': 0.5.1
    '@changesets/cli': 2.29.7
    turbo: 2.5.8
  prod:
    '@clack/prompts': 0.11.0
    c12: 3.3.1
    cac: 6.7.14
    consola: 3.4.2
    defu: 6.1.4
    farver: 0.4.2
    zod: 4.1.12
  templates:
    '@actions-sdk/esbuild-builder': latest
    '@actions-sdk/rolldown-builder': latest
    '@actions-sdk/rollup-builder': latest
    '@actions-sdk/rspack-builder': latest
    '@actions-sdk/vite-builder': latest
    '@actions-sdk/webpack-builder': latest
    actions-kit: latest
  testing:
    '@vitest/coverage-v8': 3.2.4
    vitest: 3.2.4
    vitest-testdirs: 4.3.0
  types:
    '@types/js-yaml': 4.0.9
    '@types/node': 22.18.12
  unplugin:
    '@rollup/pluginutils': 5.3.0
    js-yaml: 4.1.0
    ts-loader: 9.5.4
    tslib: 2.8.1
    unplugin: 2.3.10

engineStrict: true

linkWorkspacePackages: true

overrides:
  vite: catalog:builders

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: false
