name: Actions Kit Webpack Example
description: An Action built using Actions Kit with Webpack Builder
author: luxass
branding:
  color: purple
  icon: package
inputs:
  name:
    required: true
    default: World
    description: Your name
runs:
  using: node20
  main: dist/index.cjs
