/* eslint-disable */
// @ts-nocheck
// generated by 'actions-kit'

import type * as core from "@actions/core";

declare global {
  export const ACTION_INPUTS = {
    "name": "name",
  };

}

declare module "@actions/core" {

  type ActionInputName = "name";

  export function getInput(name: ActionInputName, options?: core.InputOptions): string;


}
