name: Actions Kit Playground
description: An Action built using Actions Kit

author: luxass
branding:
  color: purple
  icon: package

inputs:
  name:
    description: 'Your name'
    required: true
    default: 'World'

runs:
  using: node20
  main: dist/index.cjs
