name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4.2.1

      - name: print event
        run: |
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_ATTEMPT
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTION
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTION_REPOSITORY
          echo $GITHUB_ACTION_REF
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF_TYPE
          echo $GITHUB_JOB
          echo $GITHUB_REPOSITORY_OWNER
          echo $GITHUB_RETENTION_DAYS
          echo $RUNNER_PERFLOG
          echo $RUNNER_TRACKING_ID
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_SERVER_URL
          echo $GITHUB_API_URL
          echo $GITHUB_GRAPHQL_URL

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test

      - name: typecheck
        run: pnpm typecheck
