name: cleanup cache

on:
  schedule:
    - cron: "0 11 * * *" # runs every day at 11:00 UTC
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: cleanup caches older than 5 days
        uses: luxass/purge-action-cache@8203fbc1edd23369505f170a1d54074195a59c58 # v0.3.0
        with:
          max-age: 432000
