name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build:all

  esbuild:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (esbuild)
        uses: ./examples/esbuild

  rolldown:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (rolldown)
        uses: ./examples/rolldown

  rollup:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (rollup)
        uses: ./examples/rollup

  rspack:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (rspack)
        uses: ./examples/rspack

  vite:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (vite)
        uses: ./examples/vite

  webpack:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Hello World (webpack)
        uses: ./examples/webpack
